Milestone 2
mcihadkurel/Stayintouch pull request #2
Opened 2020-11-06 07:44 UTC by Amita-Roy

2020-11-09 15:39 UTC, rOluochKe requested changes
Hello Team
### You have done well so far :clap: However, you have a few issues to fix:-
- [ ] When you send a friend request, let the other person have the choice to either accept or reject the request.
### Make the change and fix the issue. Submit for another code review.
- Good luck

2020-11-09 16:01 UTC, Amita-Roy commented
Hi, we have already implemented this feature. Please refer the below screenshot.

![Screenshot 2020-11-09 at 9 28 47 PM](https://user-images.githubusercontent.com/47393794/98564817-d9f32800-22d2-11eb-9bae-3aaed2ba598d.png)

2020-11-09 18:00 UTC, tirthajyoti-ghosh requested changes
# Changes required 🛑 

## Impressive progress so far 💪! Thanks for making all the changes 👏.

### However, we need to work on some changes before we can merge.

- The timeline should only contain posts from the logged-in user and their friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)). Right now, it shows all posts, regardless of friendship status.

  - [ ] Please implement this functionality.

- Thanks for showing the screenshot. But I am not seeing the functionality implemented in your project. When I send a friend request to another user, I only see the "Pending requests" h3 tag. I don't see any list. You have implemented this functionality (saw the code) but it doesn't seem to be working. I have left some comments down below. Please check them out.

That's it!

Your project looks absolutely fantastic. Just make these changes and apply for another code review.

Happy coding 👨‍💻 

*Need help? Shoot me a message on Slack - [@Ghosh](https://app.slack.com/client/T47CT8XPG/DRDM6LAQN/user_profile/URB1MHXK6)*
<hr>

**Tirthajyoti Ghosh**

[GitHub](https://github.com/tirthajyoti-ghosh) | [LinkedIn](https://www.linkedin.com/in/tirthajyoti-ghosh/) | [Twitter](https://twitter.com/terrific_ghosh)

2020-11-09 18:00 UTC, tirthajyoti-ghosh commented on app/controllers/friendships_controller.rb
> +  end
If you look at line 5, you are setting the `confirmed` column to `true` when any user sends a friend request. This shouldn't be the case. When a user sends a friend request, the `confirmed` column should be set to false, as sending a request does not "confirm" friendship.

2020-11-09 18:00 UTC, tirthajyoti-ghosh commented on app/controllers/friendships_controller.rb
> +  end
In the `update` action, the `confirmed` column should be set to `true` instead of `false` as the update action is called when a user accepts a friendship. This is because accepting a friendship means "confirm"ing a friendship.

When I changed the values of `confirmed` in here and in `create`  action, I was able to see the pending requests list, just like your screenshot.

2020-11-09 22:15 UTC, blackpintz requested changes
# Status: Changes Required

## Hello team,

**Great job implementing the changes. However, there are still a few fixes needed.**

1). **You haven't implemented the following change as requested by the previous tse.**

- The timeline should only contain posts from the logged-in user and their friends ([screenshot ](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)). Right now, it shows all posts, regardless of friendship status.

  

- [x] Please implement this functionality.

2). **After the add friend button is clicked, it should be disabled or changed to a notification that a friend request is sent. Otherwise, a user can click it multiple times and end up sending multiple friend requests to the same person.**

3). **Jen sends Ken a friend request. When Ken logs in he should see an accept button and ignore button in his profile page and next to Jen's name on the all users page.**

4). **Also,  users should not see each other's posts when they visit each other's profile unless it is their own profile or confirmed friends.**

## Happy coding 😃.

**PS: You can reach me on slack(Rose Wanjohi).**

2020-11-10 07:33 UTC, Joseph-Burke commented
**Peer-To-Peer Code Review** - Kermits #126

Friendship requests are working but when a friendship request is sent from the user index page, the page should immediately reflect that, perhaps with a badge saying "Friendship request pending/sent".

Users should be restricted from sending friendship requests to users who have sent them an unconfirmed request, since this creates the risk of duplicate entries in the database.

Your knowledge of the project is really solid, good luck getting it approved!

2020-11-10 15:32 UTC, Amita-Roy commented
### As per the last review all the four points has been corrected and implemented

1. 
> On timeline current user can see his and his friends posts

2. 
> button status has been changed for pending request status

3.
> Accept and reject buttons are showing on all users page and user detail page

4.
> Current user cannot see other users posts on user detail page

2020-11-10 16:28 UTC, lekegitrepo requested changes
## Status: Request changes :heavy_check_mark: 
#### Good job :+1: This project is approved :heavy_check_mark:

#### _Reviewed by Temitayo Adeleke_

2020-11-10 17:03 UTC, merged